export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ITEMS_HAS_REMOVED = 'ITEM_HAS_REMOVED';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCED';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT = 'LOGOUT';